### ISSUE TITLE
بک اند پروژه

### ISSUE THREAD

**Issue by khadem-mh** [alirezaaa1194/sabzlearn2#2]
سلام خسته نباشید 
برام سوال پیش اومده که چطور بک اند پروژه تون در github.io تونستین match کنین با front پروژه؟
چون تا جایی که میدونم github pages برای deploy پروژه استاتیک هست ولی من لینک رو که چک کردم قشنگ با بک اند تعامل داشت برام سواله شما به چه روشی تونستین فرانت و بک رو با هم دیگه ارتباط بدین ؟
و این که از چه دیتابیسی استفاده می کنین؟

**Comment by alirezaaa1194** [comment]
> سلام خسته نباشید برام سوال پیش اومده که چطور بک اند پروژه تون در github.io تونستین match کنین با front پروژه؟ چون تا جایی که میدونم github pages برای deploy پروژه استاتیک هست ولی من لینک رو که چک کردم قشنگ با بک اند تعامل داشت برام سواله شما به چه روشی تونستین فرانت و بک رو با هم دیگه ارتباط بدین ؟ و این که از چه دیتابیسی استفاده می کنین

**Comment by alirezaaa1194** [comment]
سلام دوست عزیز وقتت بخیر.
بک اند و دیتابیس پروژه توی لیارا هست و فقط فرانتش توی گیتهابه چون بک اند
آنلاین هست، لینکش رو دادم به فرانت.
از دیتابیس mongoDb استفاده کردم.
